// Generated by https://quicktype.io

import { ActionExecuted } from "./ActionExecuted.interface";
import { ClusteredError } from "./Application.interface";
import { CauseError } from "./CauseError.interface";
import { StateRaizal } from "./StateRaizal.interface";
import { Analyst } from "./solutionManager.interface";

export interface Incident {
    id:                    number;
    diagnosis:             string;
    date:                  string;
    solution:              string;
    confirmed_operability: boolean;
    access_oc:             string;
    application:           string;
    clusteredError:        ClusteredError;
    causeError:            CauseError;
    actionExecuted:        ActionExecuted;
    analyst:               Analyst;
    stateRaizal:           StateRaizal;
}
